name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0

    - name: Tests
      run: |
        sudo /etc/init.d/mysql start
        go test -v ./...
