name: Build & Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Start Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: true
        redis-port: 6379
        redis-version: latest
        redis-conf: 'requirepass RedisPassw0rd'

    - name: Tests
      run: |
        sudo /etc/init.d/mysql start
        go test -race -timeout 30s -count 1 ./...
