name: Build & Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Start Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: true
        redis-port: 6379
        redis-version: '6.2'
        redis-conf: 'requirepass RedisPassw0rd'

    - name: Start MySQL
      run: sudo /etc/init.d/mysql start

    - name: Tests
      run: |
        go install github.com/jstemmer/go-junit-report@latest
        go test -race -timeout 30s -count 1 -v ./... | go-junit-report -set-exit-code > "$RUNNER_TEMP/report.xml"


    - name: Test Summary
      uses: test-summary/action@v1
      with:
        paths: |
          ${{ env.RUNNER_TEMP }}/report.xml
      if: always()